name: algon_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  
  # Networking
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Location Services
  geolocator: ^12.0.0
  
  # Biometric Authentication
  local_auth: ^2.3.0
  
  flutter_svg: ^2.0.10+1
  
  # skeletonizer: ^2.0.0  # Temporarily disabled - requires Flutter 3.31+
  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  auto_route: ^9.0.0
  file_picker: ^8.1.2
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.1
  pinput: ^6.0.1
  shimmer: ^3.0.0

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/nigeria-flag.png'
  min_sdk_android: 21 
  flutter_lints: ^4.0.0
  
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^9.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


